/* generated from Designfiles Public by generate_data_designfles */
require ('frameworks.rainbow.c');
require ('frameworks.rainbow.coffeescript');
require ('frameworks.rainbow.csharp');
require ('frameworks.rainbow.css');
require ('frameworks.rainbow.d');
require ('frameworks.rainbow.go');
require ('frameworks.rainbow.harescript');
require ('frameworks.rainbow.haskell');
require ('frameworks.rainbow.html');
require ('frameworks.rainbow.java');
require ('frameworks.rainbow.javascript');
require ('frameworks.rainbow.lua');
require ('frameworks.rainbow.php');
require ('frameworks.rainbow.python');
require ('frameworks.rainbow.r');
require ('frameworks.rainbow.ruby');
require ('frameworks.rainbow.scheme');
require ('frameworks.rainbow.shell');
require ('frameworks.rainbow.smalltalk');
/*! LOAD: frameworks.rainbow.c
    LOAD: frameworks.rainbow.coffeescript
    LOAD: frameworks.rainbow.csharp
    LOAD: frameworks.rainbow.css
    LOAD: frameworks.rainbow.d
    LOAD: frameworks.rainbow.go
    LOAD: frameworks.rainbow.harescript
    LOAD: frameworks.rainbow.haskell
    LOAD: frameworks.rainbow.html
    LOAD: frameworks.rainbow.java
    LOAD: frameworks.rainbow.javascript
    LOAD: frameworks.rainbow.lua
    LOAD: frameworks.rainbow.php
    LOAD: frameworks.rainbow.python
    LOAD: frameworks.rainbow.r
    LOAD: frameworks.rainbow.ruby
    LOAD: frameworks.rainbow.scheme
    LOAD: frameworks.rainbow.shell
    LOAD: frameworks.rainbow.smalltalk
!*/
